apiVersion: apps/v1
kind: Deployment
metadata:
  name: post_backend_21i1184-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post_backend_21i1184
  template:
    metadata:
      labels:
        app: post_backend_21i1184
    spec:
      containers:
      - name: post_backend_21i1184-container
        image: muhammadranaumerofficial754/post_backend_21i1184:latest
        ports:
        - containerPort: 8415
      nodeSelector:
        kubernetes.io/hostname: scd-assig03-cluster-m02       
